--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/20/2023 12:18:30 PM
-- Server version: 10.10.2
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ocrutil;

--
-- Drop table `archive_history`
--
DROP TABLE IF EXISTS archive_history;

--
-- Drop table `auth_groups_users`
--
DROP TABLE IF EXISTS auth_groups_users;

--
-- Drop table `auth_identities`
--
DROP TABLE IF EXISTS auth_identities;

--
-- Drop table `auth_logins`
--
DROP TABLE IF EXISTS auth_logins;

--
-- Drop table `auth_permissions_users`
--
DROP TABLE IF EXISTS auth_permissions_users;

--
-- Drop table `auth_remember_tokens`
--
DROP TABLE IF EXISTS auth_remember_tokens;

--
-- Drop table `auth_token_logins`
--
DROP TABLE IF EXISTS auth_token_logins;

--
-- Drop table `exception_queue`
--
DROP TABLE IF EXISTS exception_queue;

--
-- Drop table `migrations`
--
DROP TABLE IF EXISTS migrations;

--
-- Drop table `posts`
--
DROP TABLE IF EXISTS posts;

--
-- Drop table `settings`
--
DROP TABLE IF EXISTS settings;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `document_history_detail`
--
DROP TABLE IF EXISTS document_history_detail;

--
-- Drop table `document_history`
--
DROP TABLE IF EXISTS document_history;

--
-- Set default database
--
USE ocrutil;

--
-- Create table `document_history`
--
CREATE TABLE document_history (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  post varchar(2) NOT NULL,
  summary_confidence_score decimal(3, 2) DEFAULT NULL,
  image_resource_name varchar(2048) NOT NULL,
  processed_on datetime DEFAULT NULL,
  created_at datetime NOT NULL,
  created_by varchar(255) NOT NULL,
  ocr_payload mediumtext DEFAULT NULL,
  ocr_map_resource_name varchar(2048) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `IDX_document_history_created_at` on table `document_history`
--
ALTER TABLE document_history
ADD INDEX IDX_document_history_created_at (created_at);

--
-- Create table `document_history_detail`
--
CREATE TABLE document_history_detail (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  document_history_id int(11) UNSIGNED NOT NULL,
  summary_confidence_score decimal(3, 2) DEFAULT NULL,
  action_taken varchar(2048) NOT NULL,
  created_at datetime NOT NULL,
  created_by varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `IDX_document_history_detail_created_at` on table `document_history_detail`
--
ALTER TABLE document_history_detail
ADD INDEX IDX_document_history_detail_created_at (created_at);

--
-- Create foreign key
--
ALTER TABLE document_history_detail
ADD CONSTRAINT FK_document_history_detail_document_history_id FOREIGN KEY (document_history_id)
REFERENCES document_history (id) ON DELETE CASCADE;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(30) DEFAULT NULL,
  status varchar(255) DEFAULT NULL,
  status_message varchar(255) DEFAULT NULL,
  active tinyint(1) NOT NULL DEFAULT 0,
  last_active datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 26,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `username` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX username (username);

--
-- Create table `settings`
--
CREATE TABLE settings (
  id int(9) NOT NULL AUTO_INCREMENT,
  class varchar(255) NOT NULL,
  `key` varchar(255) NOT NULL,
  value text DEFAULT NULL,
  type varchar(31) NOT NULL DEFAULT 'string',
  context varchar(255) DEFAULT NULL,
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `posts`
--
CREATE TABLE posts (
  post_code varchar(2) NOT NULL,
  PRIMARY KEY (post_code)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `migrations`
--
CREATE TABLE migrations (
  id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  version varchar(255) NOT NULL,
  class varchar(255) NOT NULL,
  `group` varchar(255) NOT NULL,
  namespace varchar(255) NOT NULL,
  time int(11) NOT NULL,
  batch int(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `exception_queue`
--
CREATE TABLE exception_queue (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  post varchar(2) NOT NULL,
  summary_confidence_score decimal(3, 2) DEFAULT 0.00,
  image_resource_name varchar(2048) NOT NULL,
  processed_on datetime DEFAULT NULL,
  created_at datetime NOT NULL,
  created_by varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 55,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `IDX_exception_queue_created_at` on table `exception_queue`
--
ALTER TABLE exception_queue
ADD INDEX IDX_exception_queue_created_at (created_at);

--
-- Create index `IDX_exception_queue_post` on table `exception_queue`
--
ALTER TABLE exception_queue
ADD INDEX IDX_exception_queue_post (post);

--
-- Create index `IDX_document_history_post` on table `exception_queue`
--
ALTER TABLE exception_queue
ADD INDEX IDX_document_history_post (post);

--
-- Create table `auth_token_logins`
--
CREATE TABLE auth_token_logins (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ip_address varchar(255) NOT NULL,
  user_agent varchar(255) DEFAULT NULL,
  id_type varchar(255) NOT NULL,
  identifier varchar(255) NOT NULL,
  user_id int(11) UNSIGNED DEFAULT NULL,
  date datetime NOT NULL,
  success tinyint(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `user_id` on table `auth_token_logins`
--
ALTER TABLE auth_token_logins
ADD INDEX user_id (user_id);

--
-- Create index `id_type_identifier` on table `auth_token_logins`
--
ALTER TABLE auth_token_logins
ADD INDEX id_type_identifier (id_type, identifier);

--
-- Create table `auth_remember_tokens`
--
CREATE TABLE auth_remember_tokens (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  selector varchar(255) NOT NULL,
  hashedValidator varchar(255) NOT NULL,
  user_id int(11) UNSIGNED NOT NULL,
  expires datetime NOT NULL,
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 19,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `selector` on table `auth_remember_tokens`
--
ALTER TABLE auth_remember_tokens
ADD UNIQUE INDEX selector (selector);

--
-- Create index `auth_remember_tokens_user_id_foreign` on table `auth_remember_tokens`
--
ALTER TABLE auth_remember_tokens
ADD INDEX auth_remember_tokens_user_id_foreign (user_id);

--
-- Create table `auth_permissions_users`
--
CREATE TABLE auth_permissions_users (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id int(11) UNSIGNED NOT NULL,
  permission varchar(255) NOT NULL,
  created_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `auth_permissions_users_user_id_foreign` on table `auth_permissions_users`
--
ALTER TABLE auth_permissions_users
ADD INDEX auth_permissions_users_user_id_foreign (user_id);

--
-- Create table `auth_logins`
--
CREATE TABLE auth_logins (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ip_address varchar(255) NOT NULL,
  user_agent varchar(255) DEFAULT NULL,
  id_type varchar(255) NOT NULL,
  identifier varchar(255) NOT NULL,
  user_id int(11) UNSIGNED DEFAULT NULL,
  date datetime NOT NULL,
  success tinyint(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 320,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `user_id` on table `auth_logins`
--
ALTER TABLE auth_logins
ADD INDEX user_id (user_id);

--
-- Create index `id_type_identifier` on table `auth_logins`
--
ALTER TABLE auth_logins
ADD INDEX id_type_identifier (id_type, identifier);

--
-- Create table `auth_identities`
--
CREATE TABLE auth_identities (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id int(11) UNSIGNED NOT NULL,
  type varchar(255) NOT NULL,
  name varchar(255) DEFAULT NULL,
  secret varchar(255) NOT NULL,
  secret2 varchar(255) DEFAULT NULL,
  expires datetime DEFAULT NULL,
  extra text DEFAULT NULL,
  force_reset tinyint(1) NOT NULL DEFAULT 0,
  last_used_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
AVG_ROW_LENGTH = 862,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `type_secret` on table `auth_identities`
--
ALTER TABLE auth_identities
ADD UNIQUE INDEX type_secret (type, secret);

--
-- Create index `auth_identities_user_id_foreign` on table `auth_identities`
--
ALTER TABLE auth_identities
ADD INDEX auth_identities_user_id_foreign (user_id);

--
-- Create table `auth_groups_users`
--
CREATE TABLE auth_groups_users (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id int(11) UNSIGNED NOT NULL,
  `group` varchar(255) NOT NULL,
  created_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 50,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `auth_groups_users_user_id_foreign` on table `auth_groups_users`
--
ALTER TABLE auth_groups_users
ADD INDEX auth_groups_users_user_id_foreign (user_id);

--
-- Create table `archive_history`
--
CREATE TABLE archive_history (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  post varchar(2) NOT NULL,
  summary_confidence_score decimal(3, 2) DEFAULT NULL,
  image_resource_name varchar(2048) NOT NULL,
  archived_to_resource_name varchar(2048) NOT NULL,
  archived_on datetime DEFAULT NULL,
  imported_on datetime DEFAULT NULL,
  processed_on datetime DEFAULT NULL,
  created_at datetime NOT NULL,
  created_by varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `IDX_archive_history_created_at` on table `archive_history`
--
ALTER TABLE archive_history
ADD INDEX IDX_archive_history_created_at (created_at);

--
-- Create index `IDX_archive_history_processed_on` on table `archive_history`
--
ALTER TABLE archive_history
ADD INDEX IDX_archive_history_processed_on (processed_on DESC);

--
-- Create index `IDX_archive_history_post` on table `archive_history`
--
ALTER TABLE archive_history
ADD INDEX IDX_archive_history_post (post);

-- 
-- Dumping data for table document_history
--
INSERT INTO document_history VALUES
(50, 'JK', 0.11, 'IMAGE11', '2023-02-16 20:27:08', '2023-02-16 20:27:08', 'rvegajr', 'PAYLOAD', 'RF?'),
(51, 'JK', 0.12, 'IMAGE12', '2023-02-16 20:27:18', '2023-02-16 20:27:18', 'rvegajr', 'PAYLOAD', 'RF?');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(6, 'rvegajr', NULL, NULL, 0, NULL, '2022-10-02 23:43:10', '2022-10-02 23:43:10', NULL),
(17, 'silladmin', NULL, NULL, 0, NULL, '2022-11-08 11:12:07', '2022-11-08 11:12:07', NULL),
(18, 'silluser', NULL, NULL, 0, NULL, '2022-11-08 11:12:36', '2022-11-08 11:12:36', NULL),
(19, 'lwadmin', NULL, NULL, 0, NULL, '2022-11-08 11:13:06', '2022-11-08 11:13:06', NULL),
(20, 'lwuser', NULL, NULL, 0, NULL, '2022-11-08 11:13:36', '2022-11-08 11:13:36', NULL),
(21, 'bnadmin', NULL, NULL, 0, NULL, '2022-11-08 11:14:16', '2022-11-08 11:14:16', NULL),
(22, 'bnuser', NULL, NULL, 0, NULL, '2022-11-08 11:14:31', '2022-11-08 11:14:31', NULL),
(23, 'jkadmin', NULL, NULL, 0, NULL, '2022-11-08 11:15:03', '2022-11-08 11:15:03', NULL),
(24, 'jkuser', NULL, NULL, 0, NULL, '2022-11-08 11:15:22', '2022-11-08 11:15:22', NULL),
(25, 'admin', NULL, NULL, 0, NULL, '2022-11-08 11:16:02', '2022-11-08 11:16:02', NULL);

-- 
-- Dumping data for table settings
--
-- Table ocrutil.settings does not contain any data (it is empty)

-- 
-- Dumping data for table posts
--
INSERT INTO posts VALUES
('BN'),
('JK'),
('LW'),
('SL');

-- 
-- Dumping data for table migrations
--
-- Table ocrutil.migrations does not contain any data (it is empty)

-- 
-- Dumping data for table exception_queue
--
INSERT INTO exception_queue VALUES
(51, 'JK', 0.81, 'IMAGEFILE2', NULL, '2023-02-16 14:19:26', 'rvegajr'),
(52, 'JK', 0.81, 'IMAGEFILE2', NULL, '2023-02-16 14:19:26', 'rvegajr'),
(53, 'BN', 0.84, 'IMAGEFILE3', NULL, '2023-02-16 14:19:26', 'rvegajr'),
(54, 'JK', 0.84, 'IMAGEFILE3', NULL, '2023-02-16 14:19:26', 'rvegajr');

-- 
-- Dumping data for table document_history_detail
--
INSERT INTO document_history_detail VALUES
(50, 50, 0.22, 'NEW DOC', '2023-02-16 20:28:04', 'rvegajr'),
(51, 50, 0.23, 'MOVED DOC', '2023-02-16 20:28:12', 'rvegajr');

-- 
-- Dumping data for table auth_token_logins
--
-- Table ocrutil.auth_token_logins does not contain any data (it is empty)

-- 
-- Dumping data for table auth_remember_tokens
--
-- 
-- Dumping data for table auth_permissions_users
--
-- Table ocrutil.auth_permissions_users does not contain any data (it is empty)

-- 
-- Dumping data for table auth_identities
--

-- 
-- Dumping data for table archive_history
--
INSERT INTO archive_history VALUES
(50, 'JK', 0.00, 'IMG11', 'SYNOLOGY', '2023-02-16 20:28:51', '2023-02-16 20:28:51', '2023-02-16 20:28:51', '2023-02-16 20:28:51', 'rvegajr');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;